apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }} #named everything the same on purpose :)
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 5
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      tier: frontend
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        tier: frontend
    spec: # Pod spec
      containers:
      - name: mycontainer
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        volumeMounts:
          - name: little-volume
            mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"    
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
        - name: little-volume
          persistentVolumeClaim:
            claimName: {{ .Values.appName }}