apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageName }}
  namespace: {{ .Values.namespace }}
provisioner: k8s.io/minikube-hostpath

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageName }}
  resources:
    requests:
      storage: 1Gi